### ISSUE TITLE
Add mark lambda as static diagnotic

### ISSUE THREAD

**Issue by hankovich** [meziantou/Meziantou.Analyzer#567] opened 2023-07-21 16:21 UTC
Before

```c#
_listeners.AddOrUpdate(channelId, listener, (_, l) => l); <- lambda can be marked as static
```

After

```c#
_listeners.AddOrUpdate(channelId, listener, static (_, l) => l);
```

**Comment by meziantou** [comment] 2023-07-21 16:23
Closing as duplicate of https://github.com/meziantou/Meziantou.Analyzer/issues/369

**Closed by meziantou** 2023-07-21 16:23 UTC
