### ISSUE TITLE
rule for static lambda cant capture

### ISSUE THREAD

**Issue by EngRajabi** [meziantou/Meziantou.Analyzer#519] opened 2023-05-06 18:37 UTC
Can a roll be set for this purpose?
~~~csharp
Func<double, double> square = static x => x * x;
~~~
A static lambda can't capture local variables or instance state from enclosing scopes, but may reference static members and constant definitions.

**Comment by meziantou** [comment] 2023-05-06 23:53
I'm not sure what your request is about.
- Is it a feature request? If so, can you explain which pattern should be reported, and why?
- Is it a bug in an existing rule? [Bug report](https://github.com/meziantou/Meziantou.Analyzer/issues/new?assignees=&labels=&template=bug_report.yml)

**Comment by EngRajabi** [comment] 2023-05-07 07:20
This request is a feature.
In this feature, we will check lambda. If only its own variables were used, we should use static. This method is very efficient and has been added since version 9 of C#. With this, external variables are not tracked

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/static-anonymous-functions

**Comment by meziantou** [comment] 2023-05-07 13:57
This is a duplicate of https://github.com/meziantou/Meziantou.Analyzer/issues/369

**Closed by meziantou** 2023-05-07 13:57 UTC
