### ISSUE TITLE
New rule: discourage use of Nullable<T>.ToString()

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#476] opened 2023-03-24 12:27 UTC
I've seen some accidental usages of `Nullable<T>.ToString()` in the wild.

In my opinion, there are multiple issues with this:
* `Nullable<T>.ToString()` returns an empty string - instead of throwing an **InvalidOperationException** - when the `Nullable<T>` instance does not have a value.
* `Nullable<T>.ToString()` invokes `ToString()` on the underlying value.

This second part could also be integrated into *MA0052*, but I think it would be better to discourage this method altogether.

**Comment by drieseng** [comment] 2023-03-29 17:52
In the same line, it may be useful to discourage invoking `Nullable<T>.GetHashCode()` as that one will return zero if the instance does not have a value which can lead to hash collisions.

For example:
```c#
int x = 0;
int? y = null;

if (x.GetHashCode() == y.GetHashCode())
{
    Console.WriteLine("BOOM!");
}

**Comment by meziantou** [comment] 2023-03-31 03:02
> I've seen some accidental usages of Nullable<T>.ToString() in the wild.

Could you provide one or more examples?

> Nullable<T>.ToString() returns an empty string - instead of throwing an InvalidOperationException - when the Nullable<T> instance does not have a value.

From the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-8.0&WT.mc_id=DT-MVP-5003978#notes-to-inheritors), "Your ToString() override should not throw an exception."

> This second part could also be integrated into MA0052

I'm not sure why you suggest integrating it with [MA0052](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0052.md). Do you mean another rule?

> In the same line, it may be useful to discourage invoking Nullable<T>.GetHashCode() as that one will return zero if the instance does not have a value which can lead to hash collisions.

`GetHashCode` can have collision by design as you cannot map an infinite number of objects to distinct Int32. If 2 objects are equal, they must have the same hash code. But 2 different objects may have the same hash code. The following implementation of GetHashCode is perfectly valid `public int GetHashCode() => 0;`. You may have performance issues if you use it with an `HashSet`, but there won't be any bug as long as the `Equals` method is correctly implemented. If you need to compare 2 objects you need to use the `Equals` method.

So, I'm not sure that we want to disallow this method.

Side note: If you want to disable one method from your project, you can use. [Microsoft.CodeAnalysis.BannedApiAnalyzers](https://www.meziantou.net/the-roslyn-analyzers-i-use.htm#microsoft-codeanalys-5a99ab-2). I always use it to prevent some members such as `DateTime.Now`. On my side, I've created a NuGet package that provides common rules as described in this post: https://www.meziantou.net/sharing-coding-style-and-roslyn-analyzers-across-projects.htm

**Comment by drieseng** [comment] 2023-04-03 17:11
Another simple example of implicit use of `Nullable<T>.ToString()`:

```c#
double? value = 22.123d;
var result = "X = " + value;
```

This one is currently not flagged by **MA0075**.
I suppose that's the rule I wanted to mention instead of **MA0052**, but I don't recall (sleep deprivation kills your memory).

**Comment by meziantou** [comment] 2023-04-09 14:46
You are right, MA0011, MA0075 and MA0076 should handle `Nullable<T>` when `T` is culture-sensitive. I'll provide a PR soon.

> Shall I close this issue, and create a separate one for improving MA0075 / MA0076? Or just close this one?

You can keep this one. I'll close it when the 3 mentioned rules are updated.

**Closed** 2023-04-09 15:17 UTC
