### ISSUE TITLE
No "await using" detection/exclusion from MA0004

### ISSUE THREAD

**Issue by FreeYourMinds** [meziantou/Meziantou.Analyzer#404] opened 2022-10-21 07:40 UTC
**Context**
Rule identifier: _MA0004_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
MA0004 detects and _fixes_, when used e.g. with dotnet-format, the potentially _missing_ `.ConfigureAwait(false)` on usages
of `await using` which does not implement or expose `IAsyncDisposable` and therefore can not invoke the ConfigureAwait
extension method

**To Reproduce**
1. Build a code that uses the `await using` construct
1. Apply codefix MA004 on the `await using`  
   (assuming the async operation within the using already has a call to `ConfigureAwait`)

````c#
await using var transaction = await _dbContext.Database.BeginTransactionAsync().ConfigureAwait(false);
````
wiill be changed to 
````c#
await using var transaction = await _dbContext.Database.BeginTransactionAsync().ConfigureAwait(false).ConfigureAwait(false);
````
resulting in a `CS1929` error and therefore broken code.

**Additional context**
Also see [Using ConfigureAwait in "await using" declaration #2661](https://github.com/dotnet/csharplang/discussions/2661) in the _C# Language Design_ issues

**Comment by meziantou** [comment] 2022-10-21 16:13
The code fixer is not smart enough to detect the issue is on the `using await` instead of the await expression. It should be fixed by #405

**Closed** 2022-10-21 16:39 UTC
